# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

minimum_pre_commit_version: '2.8.2'

default_language_version:
  python: python3

default_stages: [commit]

exclude: '^example-site/themes/lektor-icon$|\.min\.js$|jquery\.stellar\.js$|icomoon\.css$|magnific-popup\.css$'


repos:
# Meta checks
- repo: meta
  hooks:
  - id: check-useless-excludes

# General fixers
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
    exclude_types: [svg]
  - id: mixed-line-ending
    name: Normalize mixed line endings
    args: [--fix=lf]
  - id: end-of-file-fixer
    exclude_types: [svg]
  - id: fix-byte-order-marker
    name: Remove Unicode BOM

# More general fixers
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.9
  hooks:
  - id: remove-tabs
    name: Replace tabs with spaces
    types: [text]
    exclude_types: [svg]
    args: [--whitespaces-count, '2']

# Check and fix spelling
- repo: https://github.com/codespell-project/codespell
  rev: v2.0.0
  hooks:
  # Define separate hooks for checking and correcting spelling errors
  # since codespell doesn't print verbose output when writing changes
  - id: codespell
    name: Check spelling
    exclude: '\.gitattributes'
  - id: codespell
    name: Fix spelling
    exclude: '\.gitattributes'
    args: [--write-changes]

# Prettify Bash scripts
- repo: https://github.com/lovesegfault/beautysh
  rev: '6.0.1'
  hooks:
  - id: beautysh
    name: Beautify Bash scripts

# Lint Bash scripts
- repo: https://github.com/openstack/bashate
  rev: '2.0.0'
  hooks:
  - id: bashate
    name: Lint Bash scripts
    stages: [manual]
    verbose: false
    args: [--max-line-length, '80']

# Lint and fix CSS with stylelint
- repo: https://github.com/awebdeveloper/pre-commit-stylelint
  rev: '0.0.2'
  hooks:
  - id: stylelint
    name: Lint and fix CSS (stylelint)
    args: [--fix, --color, --maxWarnings, '0', --report-needless-disables, --report-invalid-scope-disables, --report-descriptionless-disables]
    additional_dependencies:
    - 'stylelint@13.8.0'
    - 'stylelint-config-standard@20.0.0'
    - 'stylelint-a11y@1.2.3'
    - 'stylelint-csstree-validator@1.9.0'
    - 'stylelint-declaration-block-no-ignored-properties@2.3.0'
    - 'stylelint-no-unsupported-browser-features@4.1.4'
    - 'stylelint-order@4.1.0'
    - 'postcss'  # Manually required or a11y doesn't work properly

# Lint CSS with CSSlint
- repo: https://github.com/pre-commit/mirrors-csslint
  rev: v1.0.5
  hooks:
  - id: csslint
    name: Check CSS (CSSlint)

# Pretty-format INI
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: pretty-format-ini
    name: Format INI
    types: [text]
    files: '(?<!configs\/disqus-comments)\.(ini|lektorproject|codespellrc|gitlint)$'
    args: [--autofix]

# Lint and fix JavaScript
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v7.18.0
  hooks:
  - id: eslint
    name: Lint and fix JavaScript
    args: [--fix, --max-warnings, '0', --color]
    additional_dependencies:
    - 'eslint@7.18.0'
    - 'eslint-config-standard@16.0.2'
    - 'eslint-plugin-import@2.22.1'
    - 'eslint-plugin-node@11.1.0'
    - 'eslint-plugin-promise@4.2.1'

# Lint Jinja
- repo: https://github.com/thibaudcolas/curlylint
  rev: v0.12.0
  hooks:
  - id: curlylint
    name: Lint Jinja templates
    types: [html]
    files: 'templates/'

# Check JSON
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-json

# Add doctoc to Markdown
- repo: https://github.com/thlorenz/doctoc
  rev: v2.0.0
  hooks:
  - id: doctoc
    name: Generate Markdown ToCs
    args: [--maxlevel, '3', --update-only]

# Lint Markdown
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.26.0
  hooks:
  - id: markdownlint
    name: Lint Markdown
    # Pinned to Node 14/npm 6 to work around symlink issue on Windows
    # Otherwise pre-commit install-hooks needs to be run in an admin console
    # Or with dev mode or symlinks enabled at the OS level
    # https://github.com/pre-commit/pre-commit/issues/1681
    language_version: '14.15.0'
    args: [--fix]

# Check TOML and XML
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-toml
  - id: check-xml

# Pretty-format YAML
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: pretty-format-yaml
    name: Format Yaml
    args: [--autofix, --indent, '2', --preserve-quotes]

# Check YAML
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-yaml

# Lint YAML
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.25.0
  hooks:
  - id: yamllint
    name: Lint Yaml
    types: [yaml]
    args: [-s, -f, colored]

# Replace CRLF with LF post-prettify
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.9
  hooks:
  - id: remove-crlf
    name: Replace CRLFs with LF
    types: [text]
    exclude_types: [svg]


# General checkers

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.7.0
  hooks:
  - id: text-unicode-replacement-char
    name: Check for Unicode replacement chars

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=1025]
  - id: check-case-conflict
  - id: check-executables-have-shebangs
    exclude: 'pre\-commit\-config\.yaml'
  - id: check-merge-conflict
  - id: check-symlinks
  - id: destroyed-symlinks
  - id: no-commit-to-branch
    name: Prevent commits to wrong branch
    args: [--branch, master, --branch, legacy, --pattern, 'v?\d{1,3}\.x']


# Commit message hooks #

# Check that commit message follows basic rules
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.15.0
  hooks:
  - id: gitlint
    name: Check commit message

# Check commit message spelling
- repo: https://github.com/codespell-project/codespell
  rev: v2.0.0
  hooks:
  - id: codespell
    name: Check commit message spelling
    stages: [commit-msg]
